name = "logto-uss"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-02-04"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MfaStatus", id = "5f5b49022d1c4961bb98e4240ce84194" },
	{ binding = "LogtoAccessToken", id = "562b8b0476c64690be669426e3dace9f" },
	{ binding = "UsernameChangeTimelimit", id = "789713f8e36b4fafb537e516ec70c35b" }
]

[vars]
### WEB CLIENT VARIABLES
## All the required logto values
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
VITE_LOGTO_ENDPOINT = "https://id.floofbite.com"
# the appid of your CLIENT SPA application
VITE_LOGTO_APPID = "9yi5iaiw0l059dsu2z88g"
# the logto core resource, do not change <= this is only temporary
VITE_LOGTO_CORE_RESOURCE = "https://id.floofbite.com/api"
# the resources the user should have access to use the dashboard. Should be in array format. e.g: '["https://id.floofbite.com/api", "https://myresouce.logto.app"]'
VITE_LOGTO_RESOURCES = '["https://id.floofbite.com/api"]' # <= do not change (temporary)

## Extra endpoints
# the url that the dashboard is served from
VITE_ROOT = "https://logto-uss-60o.pages.dev"
# the endpoint of a matomo installation. if omitted matomo tracking will be disabled
VITE_MATOMO_ENDPOINT = ""
VITE_MATOMO_SITE_ID = ""

DEBUG_MODE = "true"

## Extra customisable options
# the email in the footer of the dashboard
VITE_SUPPORT_EMAIL = "help@floofbite.com"
# the url that users can visit to view the privacy policy/terms of service of your brand. needs to be a full url
VITE_LEGAL_URL = "https://go.floofbite.com/legal"

### WORKER VARIABLES
## Required Logto values
# THESE SHOULD NOT BE SET IN THE WRANGLER.TOML!!
# Please set these values using the wrangler cli: https://developers.cloudflare.com/workers/wrangler/commands/#secret
# LOGTO_APP_ID = Required
# LOGTO_APP_SECRET = Required - Set via wrangler cli!
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
LOGTO_DOMAIN = "https://id.floofbite.com"
# the default resource of your logto application. If you are on a self hosted instance it will be "https://id.floofbite.com/api", if you are using logto cloud it will look someting like "https://v12345.logto.app/api"
LOGTO_DEFAULT_RESOURCE = "https://id.floofbite.com/api"

# settings for avatar nsfw checking. use in conjunction with https://github.com/t2vee/nsfwjs-avatar-service
AVATAR_API = ""
ENABLE_NSFW_CHECK = 1

[placement]
mode = "smart"
